name: Testes de API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Start Server in Background and Run Tests
      env:
        PORT: 3000
        URL_BASE: http://localhost:3000
        ADMIN_EMAIL: admin@email.com
        ADMIN_PASSWORD: admin123
      run: |
        npm start &
        npx wait-on http://localhost:3000
        npm test
